### PR TITLE
Introduce download functionality

### PR DESCRIPTION
**Pull request by nielsboogaard**
Can be configured using the allowDownload parameter, which is default true.

### CODE REVIEW

**Comment by rikschennink** [comment]
Awesome Niels, do you have demo? I've been considering this but I'd rather expose it as a plugin as it's not something everyone needs.

**Comment by nielsboogaard** [comment]
Hi Rik,

I made it configurable, as I also had the feeling not everyone needs this.
By default the functionality it turned on, but if you prefer to have it
switched off by default, I'm happy to do so.

No demo available yet, but if you checkout my branch and run the index.html
you'll see it directly. I've added an animated gif to give you an idea of
how it looks like.

Btw, I also created another PR for your image preview plugin, see
https://github.com/pqina/filepond-plugin-image-preview/pull/21. Not sure if
you already saw that one.

Thanks for reviewing in advance!

Niels

Op vr 21 jun. 2019 om 13:29 schreef Rik <notifications@github.com>:

**Comment by rikschennink** [comment]
I'm more concerned about adding the additional weight in bits and bytes. 

I'll take a look on Monday.

**Comment by rikschennink** [comment]
It looks nice, maybe use the download icon from https://feathericons.com ? It's more in line with the other icons used. You could offer options, I think it kinda takes up a lot of space right now, having it as a tiny arrow prepended to the filename might also work.

I plan to move more functionality to plugins in the future so instead of having this in the core I'd love to have this as a plugin as well.

**Comment by nielsboogaard** [comment]
I've moved it to a separate plugin, see https://github.com/nielsboogaard/filepond-plugin-download (also includes a demo). Indeed using icons from the feather collection now, thanks for the tip!

**Comment by natterstefan** [comment]
Update: the plugin is now available here https://github.com/nielsboogaard/filepond-plugin-get-file

**Pull request closed without merging**
