### PR TITLE
feat: Allow applying additional filters during drop items

### PR DESCRIPTION
**Pull request by tzsk**
### Added
- Allow applying additional filters during files drop.
- Keep default ignore files filter in place.

### CODE REVIEW

**Comment by rikschennink** [comment]
If I understand correctly this is related to: https://github.com/pqina/filepond/issues/582 ?

**Comment by tzsk** [comment]
@rikschennink Not entirely. I'm taking this as a separate feature. A way to apply some additional filters before dropping via plugins.

Also, I guess. That #582 is a bit deeper than it appears. Cause I think that `beforeDropFile` only gets triggered if we set the option `dropValidation: true`. **Maybe I can do a separate PR where `beforeDropFile` executes regardless of `dropValidation` if you want.**

Anyway, This is a PR which lets the user modify the File Queue.

**Comment by rikschennink** [comment]
> Cause I think that beforeDropFile only gets triggered if we set the option dropValidation: true

I believe that's true, you can use `beforeAddFile` to filter all incoming files.

> A way to apply some additional filters before dropping via plugins.

Can you give me some use cases so I can better determine if the current featureset already covers this in some way.

**Comment by tzsk** [comment]
@rikschennink I've created a modified Fiddle Here: https://jsfiddle.net/tvsj2ex4/

Open Browser Console and then drop multiple files or a folder with multiple files in it, you will see that `beforeDropFile` only executes once if you return false from `beforeDropFile`.

I guess the `beforeDropFile` hook is implemented in the `Fail Fast` strategy.

**Comment by tzsk** [comment]
@rikschennink My dream would be

#### This: (Apply filter chain in an asynchronous way)

```js
    client.ondrop = (position, items) => {

        applyFilterChain('FILTER_DROPPED_ITEMS', filterItems(items)).then((filteredItems) => {
            if (!validateItems(filteredItems)) {
                api.ondragend(position);
                return;
            }
    
            currentState = 'drag-drop';
    
            api.onload(filteredItems, position);
        });
    };
```

I didn't know how well it would be received, So I decided to stick with the `Synchronous` way as it is currently.


### Usecase:

If you try and drop a folder with 500 files in it. It creates a huge list of files in the DOM and the page becomes extremely slow. If you hit 1000 then it is even slower.

#### Solution
I wanted to create a plugin that will zip the files inside a dropped folder and leave the individually selected files as-is. And enqueue the zipped file instead of those thousands of files.

**Comment by tzsk** [comment]
@rikschennink With this change, this package could be possible: https://github.com/tzsk/filepond-plugin-zipper

**Comment by tzsk** [comment]
@rikschennink Check out this cool example of zipping directories I built with Filepond: https://jsfiddle.net/avf0q1rp/

**Comment by rikschennink** [comment]
@tzsk this is still on my list to look into but I'm super busy right now.

Some quick thoughts:
- I guess we should also make this work for files added via the file input
- Same for copy paste actions (still not very well supported but could pipe results through the same function)
- Drag/drop async is only possible after files are dropped, during drag operations are sync.

**Comment by tzsk** [comment]
> @tzsk this is still on my list to look into but I'm super busy right now.
> 
> Some quick thoughts:
> - I guess we should also make this work for files added via the file input
> - Same for copy paste actions (still not very well supported but could pipe results through the same function)
> - Drag/drop async is only possible after files are dropped, during drag operations are sync.

Yup. Changes are implemented hope it's alright. @rikschennink

**Comment by rikschennink** [comment]
Checked it out, looks great!

Shall we rename to `ADD_ITEMS` as `PREPARE_OUTPUT` also doesn't have a 'FILTER' prefix.

**Comment by tzsk** [comment]
> Checked it out, looks great!
> 
> Shall we rename to `ADD_ITEMS` as `PREPARE_OUTPUT` also doesn't have a 'FILTER' prefix.

Sure @rikschennink I'm on it. That's a great suggestion.

**Comment by tzsk** [comment]
🚨 FYI: Rebased the PR 🙋

**Comment by rikschennink** [comment]
Just looking over the code one last time. I'm wondering, shouldn't we do the max files check after the filter has been applied? In your zip example this would allow max 10 zips instead of max 10 files to be zipped? Or isn't that how it works?

**Comment by tzsk** [comment]
> Just looking over the code one last time. I'm wondering, shouldn't we do the max files check after the filter has been applied? In your zip example this would allow max 10 zips instead of max 10 files to be zipped? Or isn't that how it works?

@rikschennink great question,

I've thought about that long and hard as well while making the PR. Then I decided to keep it the way Filepond currently works is just fine in my opinion. A few of the reasons that I considered are,

- Zipping is an Expensive Time-Consuming process so users should be specific about how many they want to allow.
- Also, `MAX_FILES` in this context is the maximum number of files one can drop. So that does not really depend on the specific use case like Zipping.

I thought of making this open-ended not specific to my use-case but for the broader audience in general.

**Comment by rikschennink** [comment]
@tzsk aha I get your point.

In this situation the zip takes up one "slot" so 10 files can become 1 file. But maybe unzip is possible as well? So drop 1 file and unzip to 10 files?

I think having max files check after the filter is the way to go for now.

**Comment by tzsk** [comment]
> @tzsk aha I get your point.
> 
> In this situation the zip takes up one "slot" so 10 files can become 1 file. But maybe unzip is possible as well? So drop 1 file and unzip to 10 files?
> 
> I think having max files check after the filter is the way to go for now.

@rikschennink I'm fully on board with that idea. I've implemented it as you suggested. Hope you like it 😊

**Comment by rikschennink** [comment]
I think you accidentally renamed the filter chain to `"PREPARE_OUTPUT"`, I meant using `"ADD_ITEMS"` instead of `"FILTER_ADD_ITEMS"` (lost in translation I guess ;-))

We're getting there :)

**Comment by tzsk** [comment]
> I think you accidentally renamed the filter chain to `"PREPARE_OUTPUT"`, I meant using `"ADD_ITEMS"` instead of `"FILTER_ADD_ITEMS"` (lost in translation I guess ;-))
> 
> We're getting there :)

Oops! I definitely misunderstood that. Fix Coming Up.

**Comment by rikschennink** [comment]
Great! Will merge/test on Thursday 👍

**Pull request merged**
