### PR TITLE
parallelize upload to chunk with setting "chunkParallelize": true

### PR DESCRIPTION
**Pull request by simonegosetto**
I think it's an important feature for upload performance, in my test this is a 400% more faster then the "serial" chunks upload

### CODE REVIEW

**Comment by simonegosetto** [comment]
@Akash4686 yes, this is the goal of this PR

**Comment by rikschennink** [comment]
Appreciate the PR, currently working on v5, not sure yet if I can find time to merge this.

**Comment by simonegosetto** [comment]
@rikschennink  I understand perfectly, but I recommend making an effort because it could be a feature that improves the sight of many, other libraries already have this feature

**Comment by rikschennink** [comment]
It's queued for me to further take a look at 👍

**Comment by rikschennink** [comment]
Hi @simonegosetto, just wanted to let you know that I've been pushing this forward for the past six months. At this time mainly because that way I don't forget to add it to v5. Just so you know that it's still on my radar.

**Comment by simonegosetto** [comment]
hi @rikschennink, very good thank you, let me know if I can do anything to help you.

**Comment by rikschennink** [comment]
I've added this feature to v5, it can now upload chunks in parallel.

**Comment by simonegosetto** [comment]
very good news

**Comment by simonegosetto** [comment]
when v5 will available in npm?

**Comment by rikschennink** [comment]
I really really really want to get an alpha version out there before December

**Pull request closed without merging**
