### PR TITLE
Improve TypeScript Definitions

### LINKED ISSUE #787: Typescript index.d.ts file missing fields [Bug]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I am working on an Angular project that will use FilePond. The issue that I am having is coming from the filepond source code, not ngx-filepond. 

The issue is that certain I want to use are not defined in index.d.ts so I have to resort to declaring a property as any instead of using a typesafe declaration.

Example:
image

In the source code it is missing the transfer and option parameters:
image

This is confusing since the documentation has these two parameters used for chunking.
image

Also in the documentation it talks about using patch. There is not a function for the Patch type in index.d.ts but I can use it (without compile error) if I declare my server object as type any. 

### Reproduction

This is a simple example. This would just demonstrate that it breaks unless you declare your variable as type any.

1. Create a new Angular project (or I imagine any project that uses typescript).
2. Install filepond, and ngx-filepond. 
3. Make sure you setup your Module correctly with the necessary imports.
4. In your app component import FilePondServerConfigProps from filepond.
5. Write something like this:

//This will throw an error because transfer and options is not defined in in ProcessServerConfigFunction. Remove them and it works. Change FilePondServerConfigProps to any and it works. 

 var pondServerExample: FilePondServerConfigProps = {
        server: {
          url: '/api/Example/',
          process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
            //do some stuff
          }
        }
      }

### Environment

```markdown
- Device: Laptop.
- OS: Windows 10.
- Browser: Doesn't matter. Fails compile unless you work around it.
```

### LINKED ISSUE #826: [Bug] Missing fields on FilePondOptions type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

The following Core Properties (as defined by https://pqina.nl/filepond/docs/api/instance/properties/) do not appear on the TypeScript Definition for `FilePondOptions`:
* storeAsFile
* credits

Use of these options requires casting the entire options object to `any` to satisfy the compiler, which nullifies the purpose of having a TypeScript Definition.

### Reproduction

https://github.com/spiltcoffee/filepond-test/blob/main/index.ts see 1) and 2)

### Environment

```markdown
N/A
```

### PR DESCRIPTION
**Pull request by spiltcoffee**
Fixes #787.
Fixes #826.

I'm unclear of how the additional parameters for `ProcessServerConfigFunction` are used exactly, so the jsdoc for those are incomplete. If anyone has any suggestions, happy to add them in.

### CODE REVIEW

**Comment by rikschennink** [comment]
Hey! Thanks so much. 

It looks like only the `transfer` param comment is missing. 

It's basically a way to know/store the current file chunk transfer id so we can track where we're at in the complete file upload.

**Comment by spiltcoffee** [comment]
@rikschennink Would the following suffice as a comment for the `transfer` parameter, then?

> Let Filepond know and store the current file chunk transfer id so it can track the progress of the whole file upload

**Comment by rikschennink** [comment]
I think that's fine 👍

**Comment by spiltcoffee** [comment]
@rikschennink Cool, updated the PR branch

**Pull request merged**
