### PR TITLE
drag n drop with grid or column

### PR DESCRIPTION
**Pull request by jwsinner**
Added getItemWidth function to be used in dragItem to get the number of rows and columns. Combining this information with our drag position we can find out where in the grid (column mod is a grid of one column) we are and how the index should update.

Known issue: If user drags item left or right outside of root it will continue updating the index.

### CODE REVIEW

**Comment by rikschennink** [comment]
I'm going to check this out as soon as possible

**Comment by jwsinner** [comment]
Root.rect.outer.height is being changed as the user drags down the page so the row number is being updated constantly. The issue can be fixed by getting the row number from the original root.rect.outer.height rather than the one updated on the drag event as well as maintaining a record of the original index of the file being dragged.

**Comment by rikschennink** [comment]
@jwsinner Happy to take a look but it sounds like you're going to make some additional tweaks to make that work, should I wait for that?

**Comment by jwsinner** [comment]
I've made a few tweaks locally that have moved me in the right direction but nothing super solid or clean yet. If you want to take a look at my approach you might be able to see a solution faster than I could since I'm still getting acquainted with the code.

**Comment by jwsinner** [comment]
This last commit is definitely more stable. Tested locally with grid and column view.

**Comment by rikschennink** [comment]
Awesome! Will take a look Monday morning

**Comment by rikschennink** [comment]
@jwsinner I've tested with preview plugin and without preview plugin but reordering doesn't work correctly? Not sure why.

```css
 .filepond--item {
    width: calc(50% - .5em);
}
```

```js
const pond = FilePond.create(inputElement, {
    allowMultiple: true,
    allowReorder: true,
    styleItemPanelAspectRatio: 1
});
```

**Comment by jwsinner** [comment]
Is it not working at all? I've set up a new instance with those parameters and it's working properly for me. I'm on a Windows PC using Firefox and Chrome. [Here](https://imgur.com/a/2hkIsfO) is a gif showing what I'm seeing with the settings you've provided.

**Comment by rikschennink** [comment]
@jwsinner that's so weird. I'll take a look again. I'm back in the office after Christmas.

**Comment by rikschennink** [comment]
@jwsinner I ran the build script which seems to have invalidated your changes (only altered dist files?).

Anyway, indeed this works! Nice. 

I notice in single column mode dragging an item to the top or bottom does not work correctly yet.

**Comment by jwsinner** [comment]
Awesome! I haven't seen issues with single column but I'll double check today and hopefully make another push.

**Comment by jwsinner** [comment]
Went through and edited the proper js files and added the objects necessary to make it work. Preliminary testing was good. Column mode no longer sends the file back to its pre-drag index if it goes too high or low.

**Comment by rikschennink** [comment]
@jwsinner That was indeed the issue, I'll review this as soon as possible.

**Comment by rikschennink** [comment]
@jwsinner it's still a bit dodgy with image previews. I think it might no be taking into account the space occupied by the preview?

Kapture 2020-01-16 at 12 26 12

**Comment by jwsinner** [comment]
Nice catch. I'm only using this for images so I didn't think to check it with mixed media types. I'll hopefully dig into this weekend.

**Comment by jwsinner** [comment]
Bump

**Comment by kylefoundry** [comment]
Bump +1
I've ran into this issue trying to implement a grid of image previews. Has this been resolved yet?

**Comment by jwsinner** [comment]
@kylefoundry Are you unable to get drag and drop reordering to work with your grid, or getting grids to work in general? If you want to drag and drop reorder in a grid, the latest commit on my fork of this project should be able to do it. The biggest issue I've run into is people using anything below Safari 13 won't be able to use it due to its lack of Pointer event support.

**Comment by kylefoundry** [comment]
Thanks @jwsinner. I'll give your fork a go and let you know if I have any issues 👍

**Comment by rikschennink** [comment]
@kylefoundry if there's no issues I'll run some further tests and will merge if all is fine.

**Comment by rikschennink** [comment]
@jwsinner Sorry for the crazy delay, just tested this and it works great! Can you pull latest and resolve conflicts? Then I can accept the PR and publish a new release.

**Comment by rikschennink** [comment]
I'm going to give it a try

**Pull request merged**
