### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by Hawxy**
Opening for some early feedback. Thanks to @zposten for his previous work on the react-filepond types, it covered about 50% of the current API surface and saved me a bunch of time. I left most of his docs in the new definitions for the time being.

TODO:
- [x] Some kind of proper test file
- [x] Finish updating docs (and mention default values)

Current questions:

1. Can the initial files array contain multiple different types of files (blob + mocked etc) or just multiple of a specific type?
2. Verification that the callback props are correct would be nice. Per the comment left by zposten, I have a feeling that some of them are incorrect or in the wrong order.

Fixes: #159

### CODE REVIEW

**Comment by rikschennink** [comment]
Thanks so much for working on this. I'm wondering if you've got an idea on how we can combine this with .d.ts files for the FilePond plugins? Is there someway to extend a .d.ts file type?

**Comment by Hawxy** [comment]
Yeah I did consider that. For the plugins that simply add to the configuration, we can take advantage of TS's automatic interface merging:
```ts
import 'filepond'
declare module 'filepond' {
    export interface FilePondOptionProps {
        somepluginsprops?: string;
        otherprop?: boolean;
    }
}

**Comment by rikschennink** [comment]
@Hawxy Nice! That is good news.

**Comment by Hawxy** [comment]
Pending my two questions, this should be ready to go 👍 
I've just left the tests file as a bunch of the more complex type scenarios. 

Have verified that types are being included on an `npm pack/publish`

**Comment by rikschennink** [comment]
Again, thanks so much. I just noticed the questions so I'll try to answer them as best as I can.

> Can the initial files array contain multiple different types of files (blob + mocked etc) or just multiple of a specific type? 

It can contain all kinds of different items, see [setting initial files](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#Setting-initial-files), so basically the object describes a server file but all other files in the list can be valid file sources (urls, blobs, files, etc)

> Verification that the callback props are correct would be nice. Per the comment left by zposten, I have a feeling that some of them are incorrect or in the wrong order. 

Best to follow the docs, I think the comments by @zposten are based on an earlier version of FilePond.

---

The only thing I found while browsing through the declaration file was that the ServerUrl `onload` and `onerror` callbacks should return a value, onload should return a unique file id, onerror a value describing the error. I think `any` would be fine for `onerror` and `number | string` for `onload`.

**Comment by Hawxy** [comment]
Cheers, has been updated.

**Comment by rikschennink** [comment]
Awesome, I'm about to call it a day so I'll merge this first thing Monday morning and publish a new release. Have a great weekend @Hawxy!

**Pull request merged**
