### PR TITLE
Fix images reordering for mobile devices

### PR DESCRIPTION
**Pull request by michael-rotaru-rm**
Bug: The reordering functionality is not working on mobile devices. When attempting to move a photo, it unexpectedly stops moving and remains hanging. [only tested on Safari & Chrome latest versions]
Fix: Replaced pointer MouseEvents with touch/move MouseEvents.

### CODE REVIEW

**Comment by michael-rotaru-rm** [comment]
@rikschennink can you have a look over my PR please?

**Comment by rikschennink** [comment]
I ran a quick test on iOS and it seems to work without issues?

Dropping pointer events feels like a step backward.

**Comment by michael-rotaru-rm** [comment]
@rikschennink Please check the attached demo video showcasing the bug.

[bug_filepond_mobile_image_reordering.webm](https://github.com/pqina/filepond/assets/83694340/68172eae-b888-417b-a05d-363c4db071f3)

**Comment by rikschennink** [comment]
It doesn't look right, I think you should load the image preview stylesheet.

**Comment by michael-rotaru-rm** [comment]
It doesn't have to do with images preview. I've reproduced the bug multiple times on different environments and mobile devices. Please run another test of the latest version of the module on any mobile OS having `allow Reorder: true` and try to reorder the images.

**Comment by michael-rotaru-rm** [comment]
[bug_filepond_mobile_image_reordering_2.webm](https://github.com/pqina/filepond/assets/83694340/17953052-1c13-4016-8861-16b626ef8757)

**Comment by rikschennink** [comment]
Couldn't reproduce in Android simulator / real Android device / iOS simulator & real iOS device.

Can only reproduce in Chrome dev tools.

✅ Open page in Chrome → ordering works
✅ Open page in Chrome → open dev tools → refresh page → ordering works
💥 Open page in Chrome → open dev tools → don't refresh page → ordering fails

I'm checking to see if there's anything I can see wrong or weird with the `PointerEvent` when switching to dev tools.

**Comment by rikschennink** [comment]
Fixed with `touch-action: none` CSS style on `.filepond--item` element.

**Comment by michael-rotaru-rm** [comment]
Thank you! 🙏

**Pull request closed without merging**
